name: CI/CD Build

on:
  workflow_dispatch:
  push:
    branches:
    - main
    
env:
  SOLUTION_NAME: ./SchedulingReminder.sln
  AZURE_WEBAPP_NAME: fscode
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
    
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_NAME }}
      - name: Build
        run: dotnet build ${{ env.SOLUTION_NAME }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.SOLUTION_NAME }} --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
